/** Texte des Dialogs „Neu auf der Webseite“ — eigene Datei, damit sie samt Dialog erst beim Klick geladen werden (die Seite ist nur deutsch). */
export const PT = {
  knopf: 'Neu auf der Webseite',
  neu: ' (Neues seit dem letzten Besuch)',
  kicker: 'Patch Notes',
  titel1: 'Neu auf',
  titel2: 'anime-kalender',
  schliessen: 'Schließen',
  filter: 'Filter',
  alles: 'Alles',
  feature: 'Feature',
  bugfix: 'Bugfix',
  heute: 'heute',
  gestern: 'gestern',
  highlight: 'HIGHLIGHT',
  ansehen: 'ansehen ›',
  fuss: 'Nur, was schon online ist.',
  laden: 'Lädt …',
  fehler: 'Konnte nicht geladen werden.',
  nochmal: 'Nochmal versuchen',
  leer: 'Keine Einträge.',
} as const
